services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=AshleyILoveYou21!
    ports:
      - 5433:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
